<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>annotations</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CalculationEngine\CalculationEngine.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
  </ItemGroup>

</Project>
