<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup>
        <IsTestProject>false</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChartCreator2\ChartCreator2.csproj" />
        <ProjectReference Include="..\Common\Common.csproj" />
        <ProjectReference Include="..\SimulationEngineLib\SimulationEngineLib.csproj" />
    </ItemGroup>

</Project>
