<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(LpgDotnetVersion)-windows</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- makes the .NET version from Directory.Build.props available at runtime, to locate the publish directories -->
    <AssemblyMetadata Include="LpgDotnetVersion" Value="$(LpgDotnetVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Database.Tests\Database.Tests.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
    <ProjectReference Include="..\LoadProfileGenerator\LoadProfileGenerator.csproj" />
  </ItemGroup>
  
</Project>