using System.Collections.Generic;
using System.IO;

namespace ReleaseMaker {
    public class WinLpgCopier:CopierBase {
        [JetBrains.Annotations.NotNull]
        public static List<string> CopyLpgFiles([JetBrains.Annotations.NotNull] string src, [JetBrains.Annotations.NotNull] string dst)
        {
            List<string> programFiles = new List<string>();
            var srcDi = new DirectoryInfo(src);
            Copy(programFiles, srcDi, src, dst,"Autofac.dll");
            Copy(programFiles, srcDi, src, dst,"Automation.dll");
            Copy(programFiles, srcDi, src, dst,"CalcPostProcessor.dll");
            Copy(programFiles, srcDi, src, dst,"CalculationController.dll");
            Copy(programFiles, srcDi, src, dst,"CalculationEngine.dll");
            Copy(programFiles, srcDi, src, dst,"ChartCreator2.dll");
            //Copy(programFiles, srcDi, src, dst,"ChartPDFCreator.dll");
            Copy(programFiles, srcDi, src, dst,"Common.dll");
            Copy(programFiles, srcDi, src, dst,"Database.dll");
            //Copy(programFiles, srcDi, src, dst,"SimulationEngineLib.dll");
//            Copy(programFiles, srcDi, src, dst,"System.Buffers.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Memory.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Numerics.Vectors.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Resources.Extensions.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Runtime.CompilerServices.Unsafe.dll");
            Copy(programFiles, srcDi, src, dst, "OxyPlot.Wpf.Shared.dll");


            //Copy(programFiles, srcDi, src, dst,"MigraDoc.DocumentObjectModel-wpf.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.DocumentObjectModel.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.Rendering-wpf.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.Rendering.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.RtfRendering.dll");

            //Copy(desrc, dst, "MigraDoc.DocumentObjectModel.resources.dll");
            //
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.DocumentObjectModel-gdi.dll");
            //string desrc = Path.Combine(src, "de");
            //Copy(programFiles, desrc, dst, "MigraDoc.DocumentObjectModel-gdi.resources.dll");
            //Copy(programFiles, desrc, dst, "MigraDoc.Rendering-gdi.resources.dll");
            //Copy(programFiles, desrc, dst, "MigraDoc.RtfRendering-gdi.resources.dll");
            //Copy(programFiles, desrc, dst, "PdfSharp-gdi.resources.dll");
            //Copy(programFiles, desrc, dst, "PdfSharp.Charting-gdi.resources.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.Rendering-gdi.dll");
            //Copy(programFiles, srcDi, src, dst,"MigraDoc.RtfRendering-gdi.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp-gdi.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp.Charting-gdi.dll");
            //Copy(desrc, dst, "PdfSharp.Charting.resources.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp.Charting.dll");
            //Copy(desrc, dst, "PdfSharp.resources.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp.dll");
            Copy(programFiles, srcDi, src, dst,"Newtonsoft.Json.dll");
            Copy(programFiles, srcDi, src, dst,"OxyPlot.dll");
            //Copy(programFiles, srcDi, src, dst,"OxyPlot.Pdf.dll");
            Copy(programFiles, srcDi, src, dst,"OxyPlot.Wpf.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp-wpf.dll");
            //Copy(programFiles, srcDi, src, dst,"PdfSharp.Charting-wpf.dll");
            //Copy(programFiles, srcDi, src, dst,"SettlementProcessing.dll");
            Copy(programFiles, srcDi, src, dst,"SQLite.Interop.dll");
            //Copy(programFiles, srcDi, src, dst,"sqlite3.dll");
            Copy(programFiles, srcDi, src, dst,"System.Data.SQLite.dll");
            Copy(programFiles, srcDi, src, dst,"LoadProfileGenerator.exe");
            //Copy(programFiles, srcDi, src, dst,"LoadProfileGenerator.exe.config", "4.0.3.0", "4.0.2.0");
            //Copy(programFiles, srcDi, src, dst,"SimulationEngine.exe");
            //Copy(programFiles, srcDi, src, dst,"PowerArgs.dll");
            Copy(programFiles, srcDi, src, dst,"EntityFramework.dll");
            Copy(programFiles, srcDi, src, dst,"EntityFramework.SqlServer.dll");
            Copy(programFiles, srcDi, src, dst,"JetBrains.Annotations.dll");
            Copy(programFiles, srcDi, src, dst,"System.Data.SQLite.EF6.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Data.SQLite.Linq.dll");
            //Copy(programFiles, srcDi, src, dst,"Microsoft.Bcl.AsyncInterfaces.dll");
            //Copy(programFiles, srcDi, src, dst,"Humanizer.dll");
            Copy(programFiles, srcDi, src, dst,"HarfBuzzSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"libHarfBuzzSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"libHarfBuzzSharp.dylib");
            //Copy(programFiles, srcDi, src, dst,"libSkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"libSkiaSharp.dylib");
            //Copy(programFiles, srcDi, src, dst,"Microsoft.Win32.Registry.AccessControl.dll");
            //Copy(programFiles, srcDi, src, dst,"Microsoft.Win32.Registry.dll");
            //Copy(programFiles, srcDi, src, dst,"Microsoft.Win32.SystemEvents.dll");
            //Copy(programFiles, srcDi, src, dst,"OxyPlot.SkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"SkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"SkiaSharp.HarfBuzz.dll");
            //Copy(programFiles, srcDi, src, dst,"System.CodeDom.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Configuration.ConfigurationManager.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Data.Odbc.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Data.OleDb.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Data.SqlClient.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Diagnostics.EventLog.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Diagnostics.PerformanceCounter.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Drawing.Common.dll");
            //Copy(programFiles, srcDi, src, dst,"System.IO.FileSystem.AccessControl.dll");
            //Copy(programFiles, srcDi, src, dst,"System.IO.Packaging.dll");
            //Copy(programFiles, srcDi, src, dst,"System.IO.Pipes.AccessControl.dll");
            //Copy(programFiles, srcDi, src, dst,"System.IO.Ports.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.AccessControl.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Cryptography.Cng.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Cryptography.Pkcs.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Cryptography.ProtectedData.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Cryptography.Xml.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Permissions.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Security.Principal.Windows.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.Duplex.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.Http.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.NetTcp.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.Primitives.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.Security.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceModel.Syndication.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ServiceProcess.ServiceController.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Text.Encoding.CodePages.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Threading.AccessControl.dll");
            //Copy(programFiles, srcDi, src, dst,"libSkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst,"libSkiaSharp.dll");

            //Copy(programFiles, srcDi, src, dst,"libSkiaSharp.dll");
            ////string srcarm = Path.Combine(src, "arm");
            ////string dstarm = Path.Combine(dst, "arm");
            //Copy(programFiles, srcDi, src, dst, "arm64\\libSkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst, "x64\\libSkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst, "x86\\libSkiaSharp.dll");
            //Copy(programFiles, srcDi, src, dst, "arm\\libSkiaSharp.so");
            //Copy(programFiles, srcDi, src, dst, "arm64\\libSkiaSharp.so");
            //Copy(programFiles, srcDi, src, dst, "x64\\libSkiaSharp.so");
            ////Copy(programFiles, srcDi, src, dst,"EPPlus.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Collections.Immutable.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Composition.AttributedModel.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Composition.Convention.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Composition.Hosting.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Composition.Runtime.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Composition.TypedParts.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Reflection.Metadata.dll");
            ////Copy(programFiles, srcDi, src, dst,"System.Text.Encoding.CodePages.dll");
            //Copy(programFiles, srcDi, src, dst,"System.Threading.Tasks.Extensions.dll");
            //Copy(programFiles, srcDi, src, dst,"xunit.abstractions.dll");
            ////string src64 = Path.Combine(src, "x64");
            ////Copy(programFiles, src64, dst, "sqlite3.dll");
            //Copy(programFiles, srcDi, src, dst,"System.ValueTuple.dll");
            //Copy(programFiles, srcDi, src, dst,"Utf8Json.dll");
            Copy(programFiles, srcDi, src, dst, @"LoadProfileGenerator.deps.json");
            Copy(programFiles, srcDi, src, dst, @"LoadProfileGenerator.dll");
            Copy(programFiles, srcDi, src, dst, @"LoadProfileGenerator.dll.config");
            Copy(programFiles, srcDi, src, dst, @"LoadProfileGenerator.runtimeconfig.dev.json");
            Copy(programFiles, srcDi, src, dst, @"LoadProfileGenerator.runtimeconfig.json");
            Copy(programFiles, srcDi, src, dst, @"OxyPlot.SkiaSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"SkiaSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"SkiaSharp.HarfBuzz.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ComponentModel.Composition.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ComponentModel.Composition.Registration.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Data.Odbc.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Data.OleDb.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Data.SqlClient.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Diagnostics.EventLog.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Diagnostics.PerformanceCounter.dll");
            Copy(programFiles, srcDi, src, dst, @"System.DirectoryServices.AccountManagement.dll");
            Copy(programFiles, srcDi, src, dst, @"System.DirectoryServices.Protocols.dll");
            Copy(programFiles, srcDi, src, dst, @"System.IO.Ports.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Management.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Private.ServiceModel.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Reflection.Context.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Runtime.Caching.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Security.Cryptography.Pkcs.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.Duplex.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.Http.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.NetTcp.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.Primitives.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.Security.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceModel.Syndication.dll");
            Copy(programFiles, srcDi, src, dst, @"System.ServiceProcess.ServiceController.dll");
            Copy(programFiles, srcDi, src, dst, @"System.Speech.dll");
            Copy(programFiles, srcDi, src, dst, @"Utf8Json.dll");
            Copy(programFiles, srcDi, src, dst, @"xunit.abstractions.dll");
            Copy(programFiles, srcDi, src, dst, @"xunit.runner.json");
            Copy(programFiles, srcDi, src, dst, @"xunit.runner.reporters.netcoreapp10.dll");
            Copy(programFiles, srcDi, src, dst, @"xunit.runner.utility.netcoreapp10.dll");
            Copy(programFiles, srcDi, src, dst, @"xunit.runner.visualstudio.dotnetcore.testadapter.dll");
            Copy(programFiles, srcDi, src, dst, @"ref\LoadProfileGenerator.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-arm\native\libSkiaSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-arm\native\libSystem.IO.Ports.Native.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-arm64\native\libSkiaSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-arm64\native\libSystem.IO.Ports.Native.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-musl-x64\native\libSkiaSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-x64\native\libSkiaSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-x64\native\libSystem.IO.Ports.Native.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux-x64\native\SQLite.Interop.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx\native\libHarfBuzzSharp.dylib");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx\native\libSkiaSharp.dylib");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx-x64\native\libSystem.IO.Ports.Native.dylib");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx-x64\native\SQLite.Interop.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\tizen-armel\native\libHarfBuzzSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\tizen-x86\native\libHarfBuzzSharp.so");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-arm64\native\libSkiaSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-arm64\native\sni.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x64\native\libHarfBuzzSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x64\native\libSkiaSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x64\native\sni.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x64\native\SQLite.Interop.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x86\native\libHarfBuzzSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x86\native\libSkiaSharp.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x86\native\sni.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win-x86\native\SQLite.Interop.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\freebsd\lib\netcoreapp2.0\System.Data.Odbc.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux\lib\netcoreapp2.0\System.Data.Odbc.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux\lib\netcoreapp2.0\System.DirectoryServices.Protocols.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\linux\lib\netstandard2.0\System.IO.Ports.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx\lib\netcoreapp2.0\System.Data.Odbc.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx\lib\netcoreapp2.0\System.DirectoryServices.Protocols.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\osx\lib\netstandard2.0\System.IO.Ports.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\unix\lib\netcoreapp2.1\System.Data.SqlClient.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.Data.Odbc.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.Diagnostics.EventLog.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.Diagnostics.EventLog.Messages.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.Diagnostics.PerformanceCounter.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.DirectoryServices.AccountManagement.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.DirectoryServices.Protocols.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.0\System.Management.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.1\System.Data.SqlClient.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp2.1\System.Speech.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netcoreapp3.0\System.Security.Cryptography.Pkcs.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netstandard2.0\System.Data.OleDb.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netstandard2.0\System.IO.Ports.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netstandard2.0\System.Runtime.Caching.dll");
            Copy(programFiles, srcDi, src, dst, @"runtimes\win\lib\netstandard2.0\System.ServiceProcess.ServiceController.dll");

            CheckIfFilesAreCompletelyCopied(src, programFiles);

            return programFiles;
            //Copy(programFiles, srcDi, src, dst,"netstandard.dll");
        }
    }
}