<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimulationEngineLib\SimulationEngineLib.csproj" />
    </ItemGroup>

</Project>
