<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>
<ItemGroup>
    <None Update="xunit.runner.json"> 
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="OxyPlot.Core" />
    <PackageReference Include="OxyPlot.SkiaSharp" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
  </ItemGroup>

</Project>
