<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="System.Data.SQLite" />
    <PackageReference Include="xunit.abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation\Automation.csproj" />
  </ItemGroup>

</Project>
