<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LoadProfileGenerator\profilegenerator-latest.db3" Link="profilegenerator.db3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PowerArgs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation\Automation.csproj" />
    <ProjectReference Include="..\CalculationController\CalculationController.csproj" />
    <ProjectReference Include="..\ChartCreator2\ChartCreator2.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Database\Database.csproj" />
  </ItemGroup>

</Project>
