namespace Automation {
    public enum CalcOption {
        HouseSumProfilesFromDetailedDats = 0,
        OverallDats = 1,
        OverallSum = 2,
        DetailedDatFiles = 3,
        ActionCarpetPlot = 4,
        EnergyCarpetPlot = 5,
        TimeOfUsePlot = 6,
        VariableLogFile = 7,
        ActivationsPerHour = 8,
        DaylightTimesList = 9,
        ActivationFrequencies = 10,
        //ActionsLogfile = 11,
        DeviceProfilesIndividualHouseholds = 12,
        TotalsPerLoadtype = 13,
        HouseholdContents = 14,
        TemperatureFile = 15,
        TotalsPerDevice = 16,
        EnergyStorageFile = 17,
        DurationCurve = 18,
        DesiresLogfile = 19,
        ThoughtsLogfile = 20,
        PolysunImportFiles = 21,
        CriticalViolations = 22,
        SumProfileExternalEntireHouse = 23,
        SumProfileExternalIndividualHouseholds = 24,
        WeekdayProfiles = 25,
        AffordanceEnergyUse = 26,
        TimeProfileFile = 27,
        LocationsFile = 28,
        HouseholdPlan = 29,
        DeviceProfileExternalEntireHouse = 30,
        DeviceProfileExternalIndividualHouseholds = 31,
        MakeGraphics = 32,
        MakePDF = 33,
        LocationCarpetPlot = 34,
        PersonStatus = 35,
        TransportationDeviceCarpetPlot = 36,
        LogErrorMessages = 37,
        LogAllMessages = 38,
        TransportationStatistics = 39,
        ActionsEachTimestep = 40,
        CalculationFlameChart = 41,
        SumProfileExternalIndividualHouseholdsAsJson = 42,
        JsonHouseSumFiles = 43,
        BodilyActivityStatistics = 44,
        BasicOverview = 45,
        DeviceActivations,
        LocationsEntries,
        ActionEntries,
        AffordanceTaggingSets,
        DeviceProfilesHouse,
        HouseholdSumProfilesFromDetailedDats,
        JsonHouseholdSumFiles,
        JsonDeviceProfilesIndividualHouseholds,
        TansportationDeviceJsons,
        DeviceTaggingSets,
        AffordanceDefinitions,
        JsonHouseholdSumFilesNoFlex,
        HouseholdSumProfilesCsvNoFlex,
        FlexibilityEvents
    }
}