<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Autofac" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Automation\Automation.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>
