<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Include="..\LoadProfileGenerator\profilegenerator-latest.db3" Link="profilegenerator-latest.db3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xunit.StaFact" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.Tests\Common.Tests.csproj" />
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\Database.Tests\Database.Tests.csproj" />
    <ProjectReference Include="..\SimulationEngineLib\SimulationEngineLib.csproj" />
  </ItemGroup>

</Project>
